# Configuration docs: https://golangci-lint.run/usage/configuration
# top level keywords: run linters linters-settings output issues severity
# https://json.schemastore.org/golangci-lint.json
linters-settings:
  errcheck:
    check-type-assertions: true
  gocyclo:
    # Minimal code complexity to report.
    # Default: 30 (but we recommend 10-20)
    min-complexity: 10
  errorlint:
    errorf: true
  funlen:
    lines: 100
    statements: 40
  nolintlint:
    require-explanation: true
    require-specific: true

linters:
  # Run only fast linters from enabled linters set (first run won't be fast)
  fast: true
  disable-all: true
  enable:
    # - asasalint
    # - asciicheck
    # - bidichk
    # - bodyclose
    # - containedctx
    # - contextcheck
    - cyclop
    - deadcode
    # - decorder
    # - depguard
    # - dogsled
    # - dupl
    # - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    # - execinquery
    # - exhaustive
    # - exhaustivestruct
    - exhaustruct
    - exportloopref
    # - forbidigo
    # - forcetypeassert
    - funlen
    # - gochecknoglobals
    - gochecknoinits
    # - gocognit
    - goconst
    # - gocritic
    - gocyclo
    # - godot
    # - godox
    # - goerr113
    - gofmt
    # - gofumpt
    - goheader
    - goimports
    - golint
    # - gomnd
    # - gomoddirectives
    # - gomodguard
    # - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ifshort
    - importas
    - ineffassign
    # - interfacebloat
    - interfacer
    - ireturn
    - lll
    # - loggercheck
    # - maintidx
    - makezero
    # - maligned
    - misspell
    # - nakedret
    # - nestif
    - nilerr
    - nilnil
    # - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosnakecase
    - nosprintfhostport
    # - paralleltest
    # - prealloc
    # - predeclared
    # - promlinter
    # - reassign
    - revive
    # - rowserrcheck
    - scopelint
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    # - tagliatelle
    # - testableexamples
    - testpackage
    # - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    # - usestdlibvars
    - varcheck
    # - varnamelen
    - wastedassign
    - whitespace
    # - wsl
